# -*- coding: utf-8 -*-
"""Python Course

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kpKbDHmNflLSXwyUeNFLW1nbIGHyNFtB
"""

print("my program")
print("Welcome to PLP")

x = 2
x + 2

y = 3
x + y

x + 10

_ + y

name = 'youtube'

name

name + 'rocks'

name [0]

name [6]

name [-1] ## Starts from the last

name [-2]

name [1:4]

name[0:2]

name[1:]

name[:4]

name[3:10]

'my ' + name[3:]

myname = 'Ian Marx'
len(myname)

nums = [23,12,34,56,78,90]

nums

nums[4]

nums[2:]

nums[-1]

names = ["john, kiran, Marx"]
names

mil = [nums, names]
mil

nums.append(59) ## append addas at the end

nums

nums.insert(3, 82)
nums

nums.remove(12)

nums.pop(56)
nums

nums.pop()

del nums[2:]

nums

nums.extend([59,83,90,61,17])
nums

min(nums)

max(nums)

sum(nums)

nums.sort()

nums

x = input("Enter first number")
print(type(x))
y = input("Enter second number")
z = x+y
print(z)

x = input("Enter first number")
a = int(x)
y = input("Enter second number")
b = int(y)
z = a+b
print(z)

x = int(input("Enter first number"))
y = int(input("Enter second number"))
z = x+y
print(z)

ch = input("Enter a char")
print(ch)

ch = input('Enter a char')
print(ch[0])

ch = input('Enter a char')[0]
print(ch)

result = eval(input('Enter an expr'))
print(result)

~23

56 & 78

45|35

12 ^ 13

25 ^ 30

num = input("Enter a number :")
print(num)
name = input("Enter name :")
print(name)

print("type of number", type(num))
print("type of name", type(name))

list = [1,"Hi", "Python", 5]
print(type(list))
print(list)

# Python tuple is immutable(readonly)
tup = ("Hi", "Python", 15)
print(type(tup))
print(tup)

d = {1:'Mark', 2:'Joseph', 3:'John', 4:'Mike'}
print(type(d))
print(d)

marks = int(input('Enter the marks'))
if marks > 85 and marks <= 100:
   print("Congrats you scored a grade A")
elif marks > 60 and marks <= 85:
  print("You scored a grade B +...")
elif marks > 40 and marks <= 60:
  print("You scored a grade B ...")
elif (marks > 30 and marks <= 40):
  print("You scored a grade C ...")
else:
  print("Sorry you failed!")

age = int(input("Enter your Age"))
if age >= 18:
    print("You are eligible to vote");
else:
  print("Sorry you have to wait!")

count = 0 
while (count < 3):
  count = count + 1
  print("Hello PLP")

# List of string

wordList = ['hi', 'hello', 'this', 'that', 'is', 'of']

# Point i to the last element in list

i = len(wordList) - 1 

# Iterate till 1st element and keep on decrementing i

while i >= 0 :

    print(wordList[i]) 

    i -= 1

for i in reversed(wordList) :

    print(i)

for i in range(10):
  print(i)

for i in range(11, 21, 1):
  print(i)

nl=[]
for x in range(1500, 2701):
    if (x%7==0) and (x%5==0):
        nl.append(str(x))
print (','.join(nl))

temp = input("Input the  temperature you like to convert? (e.g., 45F, 102C etc.) : ")
degree = int(temp[:-1])
i_convention = temp[-1]

if i_convention.upper() == "C":
  result = int(round((9 * degree) / 5 + 32))
  o_convention = "Fahrenheit"
elif i_convention.upper() == "F":
  result = int(round((degree - 32) * 5 / 9))
  o_convention = "Celsius"
else:
  print("Input proper convention.")
  quit()
print("The temperature in", o_convention, "is", result, "degrees.")

x = int(input("How many candies do you want?"))

i = 1
while i <= x:
  print("candy")
  i += 1

ax = 5
x = int(input("How many candies do you want?"))

i = 1
while i <= x:
  if i > ax:
    break # Stops and exits out of a loop

  print("candy")
  i += 1

print("Out of Stock")

for i in range(1, 101):

  if i%3 == 0:
     continue #skips the remaining statements
  print(i)

print("bye")

#We use pass when lets say you don't know what to write or maybe you'll write the function later

for i in range (4):
  print("#", end="")

print()

for i in range (4):
  print("#", end="")

for i in range(4):
   for j in range (4):
       print("#", end="")
   print()

for i in range(4):
   for j in range (i+1):
       print("#", end="")
   print()

for i in range(4):
   for j in range (4-i):
       print("#", end="")
   print()

n=5;
for i in range(n):
    for j in range(i):
        print ('* ', end="")
    print('')

for i in range(n,0,-1):
    for j in range(i):
        print('* ', end="")
    print('')

import random
target_num, guess_num = random.randint(1, 10), 0
while target_num != guess_num:
    guess_num = int(input('Guess a number between 1 and 10 until you get it right : '))
print('Well guessed!')

#Python program to calculate simple interest

P = float(input("Enter the principal amount : "))

N = float(input("Enter the number of years : "))

R = float(input("Enter the rate of interest : "))

#calculate simple interest by using this formula
SI = (P * N * R)/100

#print
print("Simple interest : {}".format(SI))

def sum(x, y):
    sum = x + y
    if sum in range(15, 20):
        return 20
    else:
        return sum

print(sum(10, 6))
print(sum(10, 2))
print(sum(10, 12))

l=int(input("Length : "))
w=int(input("Width : "))
area=l*w
perimeter=2*(l+w)
print("Area of Rectangle : ",area)
print("Perimeter of Rectangle : ",perimeter)

# return statement used to return a particular value

#function definition
def helloworld():
    print("Hello world")

#function calling
helloworld()

def sum():
    a = 10
    b = 20
    c = a+b
    return c
# calling sum() fuction in print statement
print("The sum is:", sum())

# self, is the object which your passing

class Computer:

  def config(self):
    print("i5", "16gb", "1TB")

comp1 = Computer()
comp2 = Computer()

Computer.config(comp1)
Computer.config(comp2)

class Computer:

  def config(self):
    print("i5", "16gb", "1TB")

Computer.config(comp1)
Computer.config(comp2)

class Time():

	def __init__(self, hours, mins):
		self.hours = hours
		self.mins = mins

	def addTime(t1, t2):
		t3 = Time(0,0)
		if t1.mins+t2.mins > 60:
			t3.hours = (t1.mins+t2.mins)/60
		t3.hours = t3.hours+t1.hours+t2.hours
		t3.mins = (t1.mins+t2.mins)-(((t1.mins+t2.mins)/60)*60)
		return t3

	def displayTime(self):
		print("Time is",self.hours,"hours and",self.mins,"minutes.")

	def displayMinute(self):
		print("(self.hours*60)+self.mins")

a = Time(2,50)
b = Time(1,20)
c = Time.addTime(a,b)
c.displayTime()
c.displayMinute()

d = {0:10, 1:20}
print(d)
d.update({2:30})
print(d)

#def file_read(fname):
#        txt = open(fname)
#        print(txt.read())

#file_read('test.txt')

# d = dict{}
# d = {"George":24, "Tom":22}
d = {}

d["George"] = 24
d["Tom"] = 32
d["Jenny"] = 16

print(d["George"])

print(d["Jenny"])

d["Jenny"] = 20

print(d["Jenny"])

# keys are commonly strings or numbers

d[10] = 100

print(d[10])

# how to iterate over key value pairs
for key, value in d.items():
    print("key:")
    print(key)
    print("value:")
    print(value)
    print("")

def add(x,y):
    return (x+y)
def subtract(x,y):
    return(x-y)

!pip install calc

import calc

print(add(10,20))

# Cosine of 0.5 radians 

print ("math.cos(0.5)") 

# Tangent of 0.23 radians 

print ("math.tan(0.23)") 

# 1 * 2 * 3 * 4 = 24 

print ("math.factorial(4)")

# importing built in module random 

import random 

# printing random integer between 0 and 5 

print("(random.randint(0, 5))") 

# print random floating point number between 0 and 1 

print("(random.random())")

# random number between 0 and 100 

print("(random.random() * 100)")

List = [1, 4, True, 800, "python", 27, "hello"] 

# using choice function in random module for choosing 

# a random element from a set such as a list 

print("(random.choice(List))")

# importing built in module datetime 

import datetime 

from datetime import date 

import time 

# Returns the number of seconds since the 

# Unix Epoch, January 1st 1970 

print("(time.time())")

# Converts a number of seconds to a date object 

print("(date.fromtimestamp(454554))")

!pip --version

!py -m venv myproject

!pip install virtualenvwrapper-win

!pip install django

